function setGraphicsDefaults
set(0,'DefaultAxesFontName','Arial', ...
    'DefaultAxesFontSize', 12,...
    'DefaultAxesFontSize', 12,...
    'DefaultAxesPlotBoxAspectRatio',[1 1 1],...
    'DefaultAxesPlotBoxAspectRatioMode','manual',...
    'DefaultAxesXGrid','on',...
    'DefaultAxesYGrid','on'...
    )
